### ISSUE TITLE
How to copy the response to the clipboard?

### ISSUE THREAD

**Issue by gajus** [mitmproxy/mitmproxy#3166]
In v2 of mitmproxy, I was able to use key binding `C` to copy the response body into my clipboard. This option does not seem to exist anymore in v4. What was it replaced with?

**Comment by kajojify** [comment]
@gajus It was replaced with `cut.clip` command. 
This command is bound to `ctrl L` (lowercase L). It is universal - you can copy any part of a flow. 
But it isn't well-documented for some reasons. This is the full list of flow parts you can copy into your clipboard -> https://github.com/mitmproxy/mitmproxy/blob/master/mitmproxy/types.py#L243-L277

We had many users' reports about inconvinience of this approach. So, maybe it will be replaced in v5.0.


**By the way**, mitmproxy has very [nice forum](https://discourse.mitmproxy.org/) exactly for such questions :wink:
So, it is recommended to ask there not development-related questions.

Best wishes.

**Comment by gajus** [comment]
> Input cut.clip @focus response.raw_content -> Enter.
> We had many users' reports about inconvinience of this approach. So, maybe it will be replaced in v5.0.

I am assuming that I can just bind this using custom bindings, right?

> By the way, mitmproxy has very nice forum exactly for such questions 😉

Getting off-topic, but it seems unnecessary to have forum when you have GitHub issues?

**Comment by gajus** [comment]
> I am assuming that I can just bind this using custom bindings, right?

You've already answered this in:

https://github.com/mitmproxy/mitmproxy/issues/2649

**Comment by mhils** [comment]
> Off-topic, but it seems unnecessary to have forum when you have GitHub issues?

Put simply: The number of support requests is overwhelming and we need this to go somewhere else. It's of course a fine line as we are generally happy to help, but the volume is unfortunately not sustainable for us.

**Comment by gajus** [comment]
> Put simply: The number of support requests is overwhelming and we need this to go somewhere else. It's of course a fine line as we are generally happy to help, but the volume is unfortunately not sustainable for us.

Don't think thats an efficient approach though...

You are just duplicating work.

You are now maintaining GitHub issues + forum.

People who do not discover/ do not get answer in forum will cross-post to GitHub issues.

There is no way to establish two-way relation between Discourse and GitHub issues (e.g. subscribe to when relevant issues are resolved).

A more efficient solution is to add more community moderators (there are a lot of projects that help to discover people who are willing to help maintaining an open-source project) and use labelling to distinguish important issues from noise. There are several browser extensions that allow you to ignore GitHub issues that have certain labels attached to them.

Just me 2 cents based on experience maintaining hundreds of open-source libraries.

**Comment by mhils** [comment]
> A more efficient solution is to add more community moderators (there are a lot of projects that help to discover people who are willing to help maintaining an open-source project) 

Do you have some pointers? We haven't been very successful on this front except for GSoC.

**Comment by gajus** [comment]
> Do you have some pointers? We haven't been very successful on this front except for GSoC.

Some good tips here:

https://opensource.guide/best-practices/

List yourself on https://www.codetriage.com/.

Organize AMA/ announce that you are seeking maintainers on https://www.reddit.com/r/Python/.

However, the most effective way would be to scrape the list of all people who have forked your project, collect emails from the GitHub profiles, and send a generic email saying that you are looking for a maintainers (including Google survey with quick 3-5 questions about their experience, the amount of time they can dedicate). I have done this before, got several complaints, but when it was escalated to GitHub's support – I was told it is fine as long as I do not contact people again if they request not to be contacted.

Regardless of what you are doing, the most important thing is to have very strictly defined guidelines/ list of tasks for maintainers.

**Comment by gajus** [comment]
> We had many users' reports about inconvinience of this approach. So, maybe it will be replaced in v5.0.

Has any decision been made about this?

I never managed to fully adopt mitmproxy v4 because compared to v2:

* it lacks the convenience of key bindings with option toggle (one key to trigger copy [url/curl/etc] menu)
* it feels clunky/ things break, e.g. Response view keeps flicking when new requests are being made

**Comment by M25A** [comment]
I am trying to use mitmproxy for importing flowreader in python 3 (Ubuntu). I am getting ImportError: cannot import name 'flowreader' by executing the following lines of code.

`from mitmproxy.flow import FlowReader`

I tried to install flow reader by "pip3 install FlowReader" but that failed. After searching I haven't got any clue on this issue. Please guide what can I do to solve it?

**Comment by gerrytan** [comment]
`cut.clip @focus response.raw_content` no longer works in 6.0.2, I just get `null` in my clipboard.

Instead I had to do `export.clip raw_response @focus`
