### ISSUE TITLE
Crash with python 3.10: '_UnixSelectorEventLoop' object has no attribute '_debug'

### ISSUE THREAD

**Issue by Xenapte** [mitmproxy/mitmproxy#5182]
#### Problem Description
On **Arch Linux WSL** after upgrading from python 3.9 to 3.10, mitmproxy/mitmweb crashes every time, either by using the one installed from pipx/pacman or the binaries from the official site.

#### Steps to reproduce the behavior:
1. Install [ArchWSL](https://github.com/yuk7/ArchWSL)
2. Install python 3.10 and mitmproxy
3. Launch mitmproxy

```
OSError: [Errno 0] Error
Exception ignored in: <function BaseEventLoop.__del__ at 0x7f0ac8634670>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/base_events.py", line 680, in __del__
    _warn(f"unclosed event loop {self!r}", ResourceWarning, source=self)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 419, in __repr__
    f'closed={self.is_closed()} debug={self.get_debug()}>'
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1900, in get_debug
    return self._debug
AttributeError: '_UnixSelectorEventLoop' object has no attribute '_debug'
```

#### System Information

`mitmproxy --version` also crashes with the same error.

**Comment by Xenapte** [comment]
Do we have any methods for fixing it? I mean, apart from downgrading python or switching a WSL distro.

**Comment by mhils** [comment]
Shot in the dark, but there are some eventloop-related changes on main. Switching to main my solve the issue by accident. Other than that you can either switch or investigate yourself and submit a fix to CPython. :)

**Comment by Xenapte** [comment]
Tried installing from main and the issue persisted :(

But I was able to run mitmproxy directly on the Windows host machine so I guess for now I'll just use that (I didn't want to switch before as it would require me reinstalling the certificate). Anyways at least that was a temporary solution for me :)

**Comment by mhils** [comment]
Thanks for the feedback! :)
